import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {compile} from '../vendor/cuda-webshader/src/compiler/compiler.js';import {executeCPU} from '../vendor/cuda-webshader/src/compiler/cpu-oracle.js';import {trackPoint,createTrackData,nearestTrack,TimeTrial} from '../src/track.js';import {DrivingInput} from '../src/input.js';
const source={car:readFileSync(new URL('../kernels/car.cu',import.meta.url),'utf8'),vehicle:readFileSync(new URL('../kernels/vehicle.cu',import.meta.url),'utf8')};for(const [f,entries]of Object.entries({car:['describeCar','sampleCar','buildCar','bakeSurface'],vehicle:['resetVehicle','stepVehicle','tireForces','integrateVehicle','buildPose','updateEffects']}))for(const entry of entries)test('CUDA compile / '+entry,()=>{const c=compile(source[f],{entry,workgroupSize:[128,1,1]});assert.ok(c.wgsl.includes('@compute'));assert.ok(!c.wgsl.includes('atomic<f32>'));});
test('Circuit is closed and metre-scaled',()=>{const a=trackPoint(0),b=trackPoint(Math.PI*2);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)<1e-8);const d=createTrackData();assert.equal(d.road.length,1024);assert.ok(d.length>1400&&d.length<2100);assert.ok(d.obstacles.every(Number.isFinite));});
test('Circuit generation deterministic',()=>assert.deepEqual(createTrackData(),createTrackData()));
test('Track resolution rejected outside limits',()=>{for(const n of [0,2,31,12.5,2049])assert.throws(()=>createTrackData(n));});
test('Nearest surface classification matches center and exterior',()=>{const d=createTrackData();assert.equal(nearestTrack(d.road,229,0).distance,0);assert.ok(nearestTrack(d.road,0,0).distance>100);});
test('Time trial needs all quarter gates',()=>{const d=createTrackData(),t=new TimeTrial(d.road);t.update(d.road[0],d.road[2],.01);for(const i of [64,128,192,0])t.update(d.road[i*4],d.road[i*4+2],.01);assert.equal(t.laps,1);assert.equal(t.last.valid,true);assert.ok(Number.isFinite(t.best));});
test('Skipping gates cannot complete a lap',()=>{const d=createTrackData(),t=new TimeTrial(d.road);for(const i of [0,192,0])t.update(d.road[i*4],d.road[i*4+2],.01);assert.equal(t.laps,0);});
test('Off-track lap marked invalid',()=>{const d=createTrackData(),t=new TimeTrial(d.road);t.update(229,0,.01);for(let i=0;i<12;i++)t.update(0,0,.05);for(const i of [64,128,192,0])t.update(d.road[i*4],d.road[i*4+2],.01);assert.equal(t.last.valid,false);assert.equal(t.best,Infinity);});
function harness(){const listeners={},doc={hidden:false,addEventListener(){},removeEventListener(){}},win={document:doc,navigator:{},addEventListener(k,v){listeners[k]=v;},removeEventListener(k){delete listeners[k];}},canvas={focus(){this.focused=true;}},events=[];return {input:new DrivingInput(canvas,{camera:()=>events.push('camera')},win),listeners,canvas,events};}
function key(code,repeat=false,target={tagName:'CANVAS'}){return {code,repeat,target,preventDefault(){this.prevented=true;}};}
test('W moves input forward and release stops',()=>{const {input,listeners}=harness();listeners.keydown(key('KeyW'));assert.equal(input.sample().drive,1);listeners.keyup(key('KeyW'));assert.equal(input.sample().drive,0);});
test('WASD and arrows map into correct local axes',()=>{const {input}=harness();for(const [k,name,value]of [['KeyA','steering',1],['KeyD','steering',-1],['KeyS','drive',-1],['ArrowUp','drive',1],['ArrowDown','drive',-1],['ArrowLeft','steering',1],['ArrowRight','steering',-1]]){input.clear();input.key(key(k),true);assert.equal(input.sample()[name],value);}});
test('Held key repeat recovers after clear',()=>{const {input}=harness();input.key(key('KeyW'),true);input.clear();input.key(key('KeyW',true),true);assert.equal(input.sample().drive,1);});
test('Missing physical key code falls back to letter',()=>{const {input}=harness();input.key({key:'W',target:{tagName:'CANVAS'},preventDefault(){}},true);assert.equal(input.sample().drive,1);});
test('Typing in controls does not drive',()=>{const {input}=harness();for(const tag of ['INPUT','SELECT','TEXTAREA'])input.key(key('KeyW',false,{tagName:tag}),true);assert.equal(input.sample().drive,0);});
test('Blur and disabling clear vehicle controls',()=>{const {input,listeners}=harness();input.key(key('KeyW'),true);listeners.blur();assert.equal(input.sample().drive,0);input.key(key('KeyW'),true);input.enabled=false;assert.equal(input.sample().drive,0);});
test('Camera repeat does not retrigger',()=>{const {input,events}=harness();input.key(key('KeyC'),true);input.key(key('KeyC',true),true);assert.deepEqual(events,['camera']);});
test('Touch pointer cancellation releases controls',()=>{const {input}=harness();input.setTouch(1,'throttle',true);input.setTouch(2,'left',true);assert.equal(input.sample().drive,1);assert.equal(input.sample().steering,1);input.setTouch(1,'throttle',false);assert.equal(input.sample().drive,0);});
test('Gamepad triggers, steering and handbrake',()=>{const {input}=harness(),buttons=Array.from({length:8},()=>({value:0,pressed:false}));buttons[7].value=.8;buttons[0].value=1;const v=input.sample([{connected:true,index:0,axes:[.55],buttons}]);assert.ok(Math.abs(v.steering+.5)<.001);assert.equal(v.drive,.8);assert.equal(v.handbrake,1);});
test('Manual shift consumed once',()=>{const {input}=harness();input.key(key('KeyE'),true);assert.equal(input.sample().shift,1);assert.equal(input.sample().shift,0);});
test('Cleanup removes window listeners',()=>{const {input,listeners}=harness();input.dispose();assert.deepEqual(listeners,{});});
test('CPU CUDA oracle generates the CAD descriptor count',()=>{const c=compile(source.car,{entry:'describeCar',workgroupSize:[1,1,1]}),parts=new Float32Array(512*40),count=new Uint32Array(1);executeCPU(c,{parts,count},{},[1]);assert.ok(count[0]>200&&count[0]<512);assert.ok(parts.every(Number.isFinite));});
