// AERIS R. Original parametric CAD, generated by CUDA WebShader at runtime.
// Metres. X right, Y up, Z forward. No imported car mesh or CPU vertex generator.
#define PI 3.14159265358979323846f
__device__ float clampf(float x,float lo,float hi){return fminf(fmaxf(x,lo),hi);}
__device__ float mixf(float a,float b,float t){return a+(b-a)*t;}
__device__ float ease(float t){t=clampf(t,0.0f,1.0f);return t*t*(3.0f-2.0f*t);}
__device__ float bump(float x,float c,float w){float d=(x-c)/w;return expf(-d*d);}
// Positive powers avoid the compiler's expensive general powf integer/f64 path.
__device__ float ppow(float x,float e){return expf(logf(fmaxf(x,0.000000001f))*e);}
__device__ float spow(float x,float e){return (x<0.0f?-1.0f:1.0f)*ppow(fabsf(x),e);}
__device__ float3 V(float x,float y,float z){return make_float3(x,y,z);}
__device__ float3 xyz(float4 p){return V(p.x,p.y,p.z);}
__device__ float3 add(float3 a,float3 b){return V(a.x+b.x,a.y+b.y,a.z+b.z);}
__device__ float3 sub(float3 a,float3 b){return V(a.x-b.x,a.y-b.y,a.z-b.z);}
__device__ float3 mul(float3 a,float s){return V(a.x*s,a.y*s,a.z*s);}
__device__ float3 cross3(float3 a,float3 b){return V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x);}
__device__ float3 unit(float3 a){return mul(a,rsqrtf(fmaxf(a.x*a.x+a.y*a.y+a.z*a.z,0.000000001f)));}
__device__ float3 mix3(float3 a,float3 b,float t){return add(a,mul(sub(b,a),t));}
__device__ float3 rot(float3 p,float3 r){float c=cosf(r.x),s=sinf(r.x);p=V(p.x,c*p.y-s*p.z,s*p.y+c*p.z);c=cosf(r.y);s=sinf(r.y);p=V(c*p.x+s*p.z,p.y,-s*p.x+c*p.z);c=cosf(r.z);s=sinf(r.z);return V(c*p.x-s*p.y,s*p.x+c*p.y,p.z);}
__device__ float3 bez(float3 a,float3 b,float3 c,float3 d,float t){float s=1.0f-t;return add(add(mul(a,s*s*s),mul(b,3.0f*s*s*t)),add(mul(c,3.0f*s*t*t),mul(d,t*t*t)));}
// Descriptor: shape/material/animated tag/nu; size/nv; position/variant;
// Euler rotation; four optional control points. Last two records reserved.
__device__ void part(float4* d,int i,int type,int mat,int tag,int nu,int nv,float3 sz,float3 p,float3 r,float variant){int o=i*10;d[o]=make_float4((float)type,(float)mat,(float)tag,(float)nu);d[o+1]=make_float4(sz.x,sz.y,sz.z,(float)nv);d[o+2]=make_float4(p.x,p.y,p.z,variant);d[o+3]=make_float4(r.x,r.y,r.z,0.0f);for(int j=4;j<10;j++)d[o+j]=make_float4(0.0f,0.0f,0.0f,0.0f);}
__device__ void box(float4* d,int i,int mat,int tag,float3 sz,float3 p,float3 r){part(d,i,31,mat,tag,24,16,sz,p,r,0.0f);}
__device__ void tube(float4* d,int i,int mat,int tag,float radius,float3 a,float3 b,float3 c,float3 e){part(d,i,35,mat,tag,32,10,V(radius,1.0f,1.0f),V(0.0f,0.0f,0.0f),V(0.0f,0.0f,0.0f),0.0f);int o=i*10;d[o+4]=make_float4(a.x,a.y,a.z,0.0f);d[o+5]=make_float4(b.x,b.y,b.z,0.0f);d[o+6]=make_float4(c.x,c.y,c.z,0.0f);d[o+7]=make_float4(e.x,e.y,e.z,0.0f);}
__device__ void rod(float4* d,int i,int mat,int tag,float radius,float3 a,float3 b){tube(d,i,mat,tag,radius,a,mix3(a,b,.33333f),mix3(a,b,.66667f),b);d[i*10].w=4.0f;}
// 0 paint,1 carbon,2 tyre,3 alloy,4 rotor,5 caliper,6 glass,7 satin black,
// 8 white light,9 tail light,10 leather,11 stitch,12 display,13 chrome,
// 14 lamp liner,15 amber,16 badge,17 mirror.
__global__ void describeCar(float4* parts,unsigned int* count){
 if(blockIdx.x!=0u||threadIdx.x!=0u)return;int id=0;float3 O=V(0.0f,0.0f,0.0f),S=V(1.0f,1.0f,1.0f);
 part(parts,id,1,0,0,96,40,S,O,O,0.0f);id++;part(parts,id,2,0,0,64,40,S,O,O,0.0f);id++;
 for(int si=0;si<2;si++){float s=si==0?-1.0f:1.0f;
  part(parts,id,3,0,0,160,24,S,O,O,s);id++;part(parts,id,4,0,0,160,32,S,O,O,s);id++;
  part(parts,id,9,6,0,56,32,S,O,O,s);id++;part(parts,id,10,7,0,64,8,S,O,O,s);id++;part(parts,id,15,1,0,64,12,S,O,O,s);id++;
  for(int axle=0;axle<2;axle++){float z=axle==0?1.34f:-1.34f;part(parts,id,11,0,0,64,8,V(.015f,1.0f,1.0f),V(s*.944f,.345f,z),O,s);id++;part(parts,id,12,7,0,64,8,V(.15f,1.0f,1.0f),V(s*.862f,.345f,z),O,s);id++;}
  tube(parts,id,7,0,.0028f,V(s*.902f,.772f,.66f),V(s*.929f,.47f,.59f),V(s*.915f,.265f,.35f),V(s*.905f,.227f,-.10f));id++;
  tube(parts,id,7,0,.0028f,V(s*.905f,.227f,-.10f),V(s*.912f,.24f,-.48f),V(s*.934f,.49f,-.79f),V(s*.938f,.808f,-.78f));id++;
  box(parts,id,7,0,V(.009f,.016f,.097f),V(s*.927f,.715f,-.53f),O);id++;box(parts,id,3,0,V(.010f,.008f,.077f),V(s*.939f,.719f,-.52f),O);id++;
  part(parts,id,16,7,0,40,24,S,O,O,s);id++;tube(parts,id,0,0,.021f,V(s*.932f,.52f,-.65f),V(s*.992f,.60f,-.82f),V(s*1.00f,.65f,-1.06f),V(s*.964f,.70f,-1.16f));id++;
  rod(parts,id,7,0,.016f,V(s*.73f,.827f,.55f),V(s*.973f,.87f,.56f));id++;part(parts,id,30,0,0,32,20,V(.141f,.047f,.091f),V(s*1.026f,.900f,.56f),O,0.0f);id++;
  box(parts,id,17,0,V(.116f,.028f,.004f),V(s*1.016f,.898f,.477f),O);id++;
  tube(parts,id,0,0,.023f,V(s*.737f,.79f,.845f),V(s*.69f,.91f,.59f),V(s*.60f,1.16f,.29f),V(s*.568f,1.192f,.17f));id++;
  tube(parts,id,0,0,.023f,V(s*.568f,1.192f,.17f),V(s*.585f,1.23f,-.13f),V(s*.606f,1.21f,-.43f),V(s*.584f,1.17f,-.66f));id++;
  tube(parts,id,0,0,.035f,V(s*.584f,1.17f,-.66f),V(s*.645f,1.05f,-.90f),V(s*.71f,.90f,-1.11f),V(s*.75f,.81f,-1.34f));id++;
  rod(parts,id,7,0,.01f,V(s*.73f,.804f,.78f),V(s*.732f,.804f,-1.15f));id++;
 }
 part(parts,id,6,6,0,64,40,S,O,O,0.0f);id++;part(parts,id,7,0,0,56,40,S,O,O,0.0f);id++;part(parts,id,8,6,0,56,40,S,O,O,0.0f);id++;
 part(parts,id,13,0,0,128,24,S,O,O,0.0f);id++;part(parts,id,14,0,0,100,24,S,O,O,0.0f);id++;
 box(parts,id,1,0,V(.92f,.02f,.16f),V(0.0f,.186f,2.16f),O);id++;box(parts,id,1,0,V(.90f,.024f,.20f),V(0.0f,.185f,-2.08f),O);id++;
 box(parts,id,7,0,V(.600f,.100f,.030f),V(0.0f,.409f,2.199f),O);id++;box(parts,id,7,0,V(.63f,.09f,.04f),V(0.0f,.39f,-2.196f),O);id++;
 for(int j=0;j<32;j++){box(parts,id,7,0,V(.004f,.083f,.008f),V(-.58f+(float)j*.0375f,.409f,2.236f),O);id++;}
 for(int j=0;j<4;j++){box(parts,id,7,0,V(.579f,.0025f,.007f),V(0.0f,.34f+(float)j*.045f,2.241f),O);id++;}
 for(int j=0;j<7;j++){box(parts,id,1,0,V(.010f,.085f,.18f),V(-.72f+(float)j*.24f,.18f,-2.14f),V(.16f,0.0f,0.0f));id++;}
 for(int si=0;si<2;si++){float s=si==0?-1.0f:1.0f;
  part(parts,id,18,14,0,44,24,S,O,O,s);id++;
  for(int l=0;l<3;l++){float x=s*(.55f+.10f*(float)l),y=.624f+.012f*(float)l,z=2.104f-.05f*(float)l;
   part(parts,id,30,3,0,24,14,V(.036f,.009f,.033f),V(x,y,z),O,0.0f);id++;part(parts,id,30,8,0,24,14,V(.020f,.005f,.019f),V(x,y+.006f,z+.004f),O,0.0f);id++;}
  tube(parts,id,8,0,.005f,V(s*.495f,.635f,2.135f),V(s*.63f,.655f,2.10f),V(s*.77f,.681f,2.035f),V(s*.849f,.674f,1.978f));id++;
  tube(parts,id,8,0,.004f,V(s*.49f,.614f,2.186f),V(s*.63f,.637f,2.155f),V(s*.76f,.652f,2.091f),V(s*.844f,.662f,2.028f));id++;
  box(parts,id,14,0,V(.365f,.043f,.034f),V(s*.497f,.695f,-2.148f),V(0.0f,-s*.08f,0.0f));id++;
  for(int j=0;j<2;j++){tube(parts,id,9,0,.008f,V(s*.13f,.701f+(float)j*.025f,-2.191f),V(s*.39f,.703f+(float)j*.025f,-2.199f),V(s*.67f,.70f+(float)j*.025f,-2.187f),V(s*.848f,.676f+(float)j*.025f,-2.129f));id++;}
  for(int ex=0;ex<2;ex++){float x=s*(.61f+(float)ex*.12f);part(parts,id,32,13,0,48,12,V(.043f,.034f,.043f),V(x,.273f,-2.246f),V(0.0f,PI*.5f,0.0f),.011f);id++;part(parts,id,34,7,0,36,6,V(.039f,.039f,.039f),V(x,.273f,-2.239f),V(0.0f,PI*.5f,0.0f),0.0f);id++;}
 }
 for(int j=0;j<8;j++){box(parts,id,7,0,V(.455f,.007f,.019f),V(0.0f,.836f-(float)j*.012f,-1.44f-(float)j*.055f),V(-.10f,0.0f,0.0f));id++;}
 part(parts,id,17,0,0,64,16,S,O,O,0.0f);id++;
 box(parts,id,7,0,V(.70f,.09f,1.10f),V(0.0f,.245f,-.10f),O);id++;
 for(int si=0;si<2;si++){float x=si==0?-.355f:.355f;part(parts,id,37,10,0,36,40,V(.235f,.48f,.49f),V(x,.30f,-.22f),O,0.0f);id++;
  for(int b=0;b<2;b++){float s=b==0?-1.0f:1.0f;part(parts,id,30,10,0,28,24,V(.056f,.20f,.155f),V(x+s*.18f,.635f,-.385f),V(-.23f,0.0f,0.0f),0.0f);id++;
   tube(parts,id,11,0,.0024f,V(x+s*.163f,.365f,.02f),V(x+s*.174f,.45f,-.2f),V(x+s*.173f,.72f,-.49f),V(x+s*.122f,.87f,-.55f));id++;}
  box(parts,id,10,0,V(.145f,.123f,.081f),V(x,.872f,-.556f),V(-.17f,0.0f,0.0f));id++;
  rod(parts,id,7,0,.012f,V(x+.17f,.79f,-.59f),V(x-.12f,.39f,-.20f));id++;
 }
 box(parts,id,10,0,V(.685f,.077f,.199f),V(0.0f,.721f,.579f),V(-.055f,0.0f,0.0f));id++;
 tube(parts,id,11,0,.003f,V(-.63f,.78f,.433f),V(-.32f,.803f,.402f),V(.32f,.803f,.402f),V(.63f,.78f,.433f));id++;
 box(parts,id,1,0,V(.102f,.116f,.42f),V(0.0f,.422f,.035f),V(-.06f,0.0f,0.0f));id++;
 box(parts,id,12,0,V(.12f,.065f,.006f),V(0.0f,.739f,.376f),V(-.09f,0.0f,0.0f));id++;box(parts,id,12,0,V(.16f,.067f,.006f),V(-.345f,.763f,.389f),O);id++;
 part(parts,id,32,10,5,64,16,V(.142f,.142f,.142f),V(-.345f,.69f,.205f),V(0.0f,PI*.5f,0.0f),.022f);id++;
 box(parts,id,7,5,V(.088f,.037f,.024f),V(-.345f,.682f,.205f),O);id++;
 for(int q=0;q<3;q++){float a=(float)q*2.094f;rod(parts,id,3,5,.008f,V(-.345f,.68f,.205f),V(-.345f+sinf(a)*.119f,.69f+cosf(a)*.119f,.205f));id++;}
 for(int j=0;j<5;j++){part(parts,id,30,3,0,16,10,V(.012f,.006f,.012f),V(0.0f,.537f,.12f-(float)j*.05f),O,0.0f);id++;}
 // Wipers rest below the windscreen sightline.
 for(int w=0;w<2;w++){float x=w==0?-.38f:.22f;rod(parts,id,7,0,.005f,V(x-.15f,.823f,.826f),V(x+.23f,.842f,.80f));id++;}
 for(int w=0;w<4;w++){float side=w%2==0?-1.0f:1.0f,z=w<2?1.34f:-1.34f,width=w<2?.24f:.282f;float3 centre=V(side*.852f,.345f,z);int tag=w+1;
  part(parts,id,39,2,tag,128,32,V(width,.337f,.337f),centre,O,side);id++;
  part(parts,id,33,3,tag,96,8,V(width*.40f,.241f,.241f),centre,O,0.0f);id++;
  for(int f=0;f<2;f++){float x=centre.x+side*(f==0?width*.42f:-width*.30f);part(parts,id,32,3,tag,96,12,V(.237f,.237f,.237f),V(x,.345f,z),O,.009f);id++;}
  part(parts,id,34,4,tag,96,16,V(.195f,.195f,.195f),V(centre.x+side*.045f,.345f,z),O,0.0f);id++;
  part(parts,id,33,7,tag,48,8,V(.055f,.069f,.069f),centre,O,0.0f);id++;
  part(parts,id,34,3,tag,48,8,V(.058f,.058f,.058f),V(centre.x+side*(width*.43f+.004f),.345f,z),O,0.0f);id++;
  for(int k=0;k<10;k++){float a=(float)(k/2)*(2.0f*PI/5.0f)+(k%2==0?-.092f:.092f);part(parts,id,38,3,tag,24,12,V(.03f,.03f,.03f),centre,O,side);parts[id*10+4]=make_float4(a,width,0.0f,0.0f);id++;}
  for(int k=0;k<5;k++){float a=(float)k*2.0f*PI/5.0f;part(parts,id,33,13,tag,12,2,V(.01f,.008f,.008f),V(centre.x+side*width*.46f,.345f+cosf(a)*.043f,z+sinf(a)*.043f),O,0.0f);id++;}
  box(parts,id,5,w+6,V(.047f,.106f,.041f),V(centre.x+side*.045f,.383f,z-.163f),V(.26f,0.0f,0.0f));id++;
  rod(parts,id,7,0,.014f,V(side*.46f,.36f,z-.17f),V(side*.79f,.36f,z));id++;rod(parts,id,7,0,.014f,V(side*.46f,.36f,z+.17f),V(side*.79f,.36f,z));id++;
 }
 box(parts,id,16,0,V(.032f,.002f,.04f),V(0.0f,.626f,2.023f),V(.12f,0.0f,0.0f));id++;
 box(parts,id,16,0,V(.185f,.041f,.003f),V(0.0f,.535f,-2.234f),O);id++;count[0]=(unsigned int)id;
}
__device__ float widthAt(float z){return .91f+.057f*bump(z,-1.35f,.60f)+.049f*bump(z,1.31f,.54f)-.12f*bump(z,2.45f,.42f)-.053f*bump(z,-2.40f,.43f)-.018f*bump(z,0.0f,.70f);}
__device__ float shoulder(float z){return .732f+.092f*bump(z,1.34f,.55f)+.12f*bump(z,-1.34f,.58f)-.14f*bump(z,2.45f,.46f)-.047f*bump(z,-2.45f,.49f);}
__device__ float3 point(const float4* d,int id,float u,float v){int o=id*10,type=(int)d[o].x;float3 sz=xyz(d[o+1]),p=xyz(d[o+2]),r=xyz(d[o+3]);float side=d[o+2].w,t=2.0f*v-1.0f;float3 q=V(0.0f,0.0f,0.0f);
 if(type==1){float z=mixf(.83f,2.258f,u),w=mixf(.716f,.658f,ease(u));float y=mixf(.788f,.582f,ease(u))+.032f*(1.0f-t*t)-.012f*bump(t,0.0f,.45f)*sinf(PI*u)+.028f*bump(fabsf(t),.81f,.10f)*sinf(PI*u);q=V(t*w,y,z);
 }else if(type==2){q=V(t*.729f,mixf(.742f,.812f,ease(u))+.024f*(1.0f-t*t),mixf(-2.235f,-1.30f,u));
 }else if(type==3){float z=mixf(-2.23f,2.26f,u),inner=.716f,center=.765f;if(z>.83f){inner=mixf(.716f,.658f,ease((z-.83f)/1.428f));center=mixf(.788f,.582f,ease((z-.83f)/1.428f));}if(z<-1.30f){inner=.729f;center=mixf(.742f,.812f,ease((z+2.235f)/.935f));}float y=shoulder(z)+.032f*sinf(v*PI)-.012f*v;q=V(side*mixf(inner,widthAt(z),v),mixf(center,y,ease(v)),z);
 }else if(type==4){float z=mixf(-2.23f,2.26f,u),b=.215f,top=shoulder(z)-.01f,dz=fminf(fabsf(z-1.34f),fabsf(z+1.34f));if(dz<.395f)b=.345f+sqrtf(fmaxf(0.0f,.395f*.395f-dz*dz));b=fminf(b,top-.003f);float x=widthAt(z)-.017f*(1.0f-v)+.022f*sinf(v*PI)-.040f*bump(v,.35f,.22f)*bump(z,-.30f,.7f);q=V(side*x,mixf(b,top,v),z);
 }else if(type==6){float a=u*2.0f-1.0f;q=V(a*mixf(.715f,.564f,v),mixf(.802f,1.194f,v)+.027f*(1.0f-a*a),mixf(.846f,.171f,v)+.035f*(1.0f-a*a));
 }else if(type==7){q=V(t*(.573f+.014f*sinf(u*PI)),1.182f+.041f*(1.0f-t*t)+.016f*sinf(u*PI),mixf(-.66f,.18f,u));
 }else if(type==8){float a=u*2.0f-1.0f;q=V(a*mixf(.723f,.573f,v),mixf(.813f,1.174f,v)+.020f*(1.0f-a*a),mixf(-1.32f,-.655f,v)-.025f*(1.0f-a*a));
 }else if(type==9){q=V(side*(mixf(.723f,.573f,v)+.016f*sinf(PI*v)),mixf(.807f,1.182f,v)+.010f*sinf(PI*u),mixf(mixf(-1.145f,.793f,u),mixf(-.65f,.172f,u),v));
 }else if(type==10){q=V(side*.727f,.798f+v*.014f,mixf(-1.16f,.82f,u));
 }else if(type==11||type==12){float a=mixf(-.135f,PI+.135f,u),rad=.399f+(type==11?v*.017f:0.0f);return add(p,V(type==12?(v-.5f)*sz.x:0.0f,sinf(a)*rad,cosf(a)*rad));
 }else if(type==13){float a=u*2.0f*PI,x=spow(cosf(a),.38f)*mixf(.59f,.886f,v),y=.409f+spow(sinf(a),.55f)*mixf(.105f,.208f,v);q=V(x,y,2.264f-.065f*(1.0f-v)-.12f*x*x*x*x+.007f*sinf(v*PI));
 }else if(type==14){float x=(u*2.0f-1.0f)*.933f;float a=x/.933f;q=V(x,mixf(.503f,.750f,v),-2.23f+.08f*a*a*a*a);
 }else if(type==15){q=V(side*(.899f+.042f*v),.203f-.021f*sinf(PI*v),mixf(-.92f,.93f,u));
 }else if(type==16){q=V(side*(.967f+.003f*sinf(v*PI)),mixf(.335f,.35f+.30f*(1.0f-u),v),mixf(-1.17f,-.67f,u));
 }else if(type==17){float x=(u*2.0f-1.0f)*.879f;q=V(x,.764f+.042f*v+.013f*(1.0f-x*x),mixf(-2.13f,-2.29f,v));
 }else if(type==18){q=V(side*mixf(.482f,.856f,u),mixf(.612f,.662f,u)+v*.022f,mixf(2.181f,2.023f,u)-v*.060f);
 }else if(type==30||type==31){float a=u*2.0f*PI,b=(v-.5f)*PI;float3 dir=V(cosf(b)*cosf(a),sinf(b),cosf(b)*sinf(a));if(type==30)q=V(dir.x*sz.x,dir.y*sz.y,dir.z*sz.z);else{float m=fmaxf(fabsf(dir.x),fmaxf(fabsf(dir.y),fabsf(dir.z))),rr=fminf(sz.x,fminf(sz.y,sz.z))*.62f;q=V(dir.x/m*(sz.x-rr)+dir.x*rr,dir.y/m*(sz.y-rr)+dir.y*rr,dir.z/m*(sz.z-rr)+dir.z*rr);}
 }else if(type==32){float a=u*2.0f*PI,b=v*2.0f*PI;q=V(side*sinf(b),(sz.y+side*cosf(b))*cosf(a),(sz.z+side*cosf(b))*sinf(a));
 }else if(type==33){float a=u*2.0f*PI;q=V((v*2.0f-1.0f)*sz.x,cosf(a)*sz.y,sinf(a)*sz.z);
 }else if(type==34){float a=u*2.0f*PI;q=V(0.0f,cosf(a)*v*sz.y,sinf(a)*v*sz.z);
 }else if(type==35){float3 a=xyz(d[o+4]),b=xyz(d[o+5]),c=xyz(d[o+6]),e=xyz(d[o+7]);float3 centre=bez(a,b,c,e,u),tangent=unit(sub(bez(a,b,c,e,u+.001f),bez(a,b,c,e,u-.001f)));float3 ref=fabsf(tangent.y)>.9f?V(1.0f,0.0f,0.0f):V(0.0f,1.0f,0.0f),x=unit(cross3(tangent,ref)),y=cross3(tangent,x);return add(centre,mul(add(mul(x,cosf(v*2.0f*PI)),mul(y,sinf(v*2.0f*PI))),sz.x));
 }else if(type==37){float a=u*2.0f-1.0f,z=0.0f,y=0.0f;if(v<.46f){float f=v/.46f;z=mixf(.26f,-.15f,f);y=.062f+.048f*bump(f,.04f,.4f);}else{float f=(v-.46f)/.54f;z=mixf(-.15f,-.34f,f);y=mixf(.07f,.50f,f);}q=V(a*sz.x,y+.041f*a*a*a*a,z);
 }else if(type==38){float a=d[o+4].x+.19f*sinf(PI*u),width=d[o+4].y,rad=mixf(.045f,.231f,u),lat=(v*2.0f-1.0f)*mixf(.015f,.020f,u);q=V(side*(width*.42f-.045f*sinf(PI*u)),cosf(a)*rad-sinf(a)*lat,sinf(a)*rad+cosf(a)*lat);
 }else if(type==39){float a=u*2.0f*PI,b=v*PI,rad=.235f+.102f*ppow(fmaxf(0.0f,sinf(b)),.38f);q=V(cosf(b)*sz.x*.5f,cosf(a)*rad,sinf(a)*rad);}
 if(type<30)return q;return add(rot(q,r),p);
}
__global__ void sampleCar(const float4* parts,const float4* jobs,float4* samples,unsigned int partCount){unsigned int id=blockIdx.x;if(id>=partCount)return;float4 j=jobs[id];unsigned int nu=(unsigned int)j.y,nv=(unsigned int)j.z,start=(unsigned int)j.w;for(unsigned int k=threadIdx.x;k<(nu+1u)*(nv+1u);k+=blockDim.x){float3 p=point(parts,(int)id,(float)(k%(nu+1u))/(float)nu,(float)(k/(nu+1u))/(float)nv);samples[start+k]=make_float4(p.x,p.y,p.z,0.0f);}}
__global__ void buildCar(const float4* parts,const float4* jobs,const float4* samples,float4* positions,float4* normals,float4* uvMeta,unsigned int partCount){
 unsigned int id=blockIdx.x;if(id>=partCount)return;float4 j=jobs[id],info=parts[id*10u];unsigned int start=(unsigned int)j.x,nu=(unsigned int)j.y,nv=(unsigned int)j.z,base=(unsigned int)j.w;int type=(int)info.x;float side=parts[id*10u+2u].w,orient=1.0f;
 if(type==3||type==11||type==15||type==38)orient=side;if(type==4||type==9||type==10||type==16)orient=-side;
 if(type==8||type==13||type==14||type==30||type==31||type==35||type==39)orient=-1.0f;if(type==34)orient=parts[id*10u+2u].x<0.0f?1.0f:-1.0f;
 for(unsigned int k=threadIdx.x;k<nu*nv*6u;k+=blockDim.x){unsigned int cell=k/6u,c=k%6u,ix=cell%nu,iy=cell/nu;unsigned int gx=ix+((c==1u||c==2u||c==4u)?1u:0u),gy=iy+((c==2u||c==4u||c==5u)?1u:0u),si=base+gy*(nu+1u)+gx;
  unsigned int left=gx>0u?si-1u:si,right=gx<nu?si+1u:si,down=gy>0u?si-nu-1u:si,up=gy<nv?si+nu+1u:si;
  float3 p=xyz(samples[si]),n=mul(unit(cross3(sub(xyz(samples[right]),xyz(samples[left])),sub(xyz(samples[up]),xyz(samples[down])))),orient);
  unsigned int dest=k;if(orient<0.0f){unsigned int t=k%3u;dest=k-t+(t==1u?2u:t==2u?1u:0u);}unsigned int o=start+dest;
  positions[o]=make_float4(p.x,p.y,p.z,info.z);normals[o]=make_float4(n.x,n.y,n.z,0.0f);uvMeta[o]=make_float4((float)gx/(float)nu,(float)gy/(float)nv,(float)type,info.y);
 }
}
__device__ unsigned int hash32(unsigned int x){x^=x>>16u;x*=2146121005u;x^=x>>15u;x*=2221713035u;x^=x>>16u;return x;}
__device__ float rnd(unsigned int n){return (float)(hash32(n)&16777215u)/16777216.0f;}
__global__ void bakeSurface(float4* colorMap,float4* normalRough,unsigned int width,unsigned int kind){unsigned int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=width*width)return;float u=((float)(i%width)+.5f)/(float)width,v=((float)(i/width)+.5f)/(float)width,n=rnd(i+kind*3271u),shade=.1f,rough=.6f,dx=0.0f,dy=0.0f;
 if(kind==0u){float a=floorf(u*16.0f)+floorf(v*16.0f),stripe=a-2.0f*floorf(a*.5f),s=stripe<1.0f?sinf(u*16.0f*PI):sinf(v*16.0f*PI);shade=.017f+.034f*fabsf(s)+.004f*n;rough=.31f;dx=.13f*cosf(u*128.0f*PI);dy=.13f*cosf(v*128.0f*PI);}
 if(kind==1u){shade=.018f+.012f*n;if(fabsf(sinf(v*8.0f*PI))<.10f||fabsf(sinf(u*72.0f*PI+v*15.0f))<.08f)shade*=.25f;rough=.82f;dx=.10f*cosf(u*144.0f*PI);dy=.15f*cosf(v*16.0f*PI);}
 if(kind==2u){shade=.040f+.010f*n;rough=.62f;dx=(n-.5f)*.25f;dy=(rnd(i+79u)-.5f)*.25f;}
 if(kind==3u){shade=.085f+.07f*n;rough=.93f;dx=(n-.5f)*.45f;dy=(rnd(i+711u)-.5f)*.45f;}
 if(kind==4u){float x=u*2.0f-1.0f,y=v*2.0f-1.0f,rr=sqrtf(x*x+y*y);shade=.21f+.10f*n+.035f*sinf(rr*600.0f);rough=.36f;dx=.045f*sinf(rr*550.0f);dy=dx;}
 if(kind==5u){shade=.78f+.22f*n;rough=.21f+.05f*n;dx=(n-.5f)*.024f;dy=(rnd(i+177u)-.5f)*.024f;}
 float3 nn=unit(V(dx,dy,1.0f));colorMap[i]=make_float4(shade,shade,shade,1.0f);normalRough[i]=make_float4(nn.x*.5f+.5f,nn.y*.5f+.5f,nn.z*.5f+.5f,rough);
}
