import * as THREE from 'three/webgpu';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GpuRuntime} from '../vendor/cuda-webshader/src/runtime/runtime.js';import {CudaCar,PAINTS} from './car.js';import {VehicleSimulation,FIXED_DT} from './simulation.js';import {Stage} from './stage.js';import {DrivingInput} from './input.js';import {EngineAudio} from './audio.js';import {createTrackData,TimeTrial,nearestTrack} from './track.js';
const $=id=>document.getElementById(id),show=(id,value=true)=>$(id).classList.toggle('hidden',!value),fmt=t=>Number.isFinite(t)?`${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(3).padStart(6,'0')}`:'—';
function download(name,data,type='application/json'){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let toastTimer;function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
const shots={hero:{p:[4.7,1.85,6.3],t:[0,.55,0],fov:36},rear:{p:[-4.8,1.75,-6.1],t:[0,.6,-.3],fov:36},side:{p:[6.6,1.05,.2],t:[0,.6,0],fov:40},wheel:{p:[2.2,.65,2.55],t:[.86,.43,1.27],fov:35},cabin:{p:[-.345,.846,.07],t:[-.345,.84,12],fov:65}};
class AerisApp{
 constructor(){this.ready=false;this.mode='garage';this.paused=false;this.photo=false;this.cameraIndex=0;this.audio=new EngineAudio();this.track=createTrackData();this.trial=new TimeTrial(this.track.road);this.frameCount=0;this.renderRate=0;this.busy=false;this.accumulator=0;this.paint='petrol';this.sources={};this.lost=false;this.previousTime=performance.now();this.statsStart=this.previousTime;this.simStart=0;this.quality='balanced';}
 async start(){if(this.ready||this.starting)return;this.starting=true;$('start').disabled=true;show('title',false);show('loading');try{
  if(!navigator.gpu)throw Error('WebGPU is not available. Open on localhost or HTTPS in a WebGPU-enabled browser.');
  const progress=s=>{$('progress').textContent=s;};this.quality=$('quality').value;this.runtime=await GpuRuntime.create({onError:e=>this.fail(e)});const r=this.renderer=new THREE.WebGPURenderer({device:this.runtime.device,antialias:true,alpha:false});r.setPixelRatio(Math.min(devicePixelRatio,this.quality==='high'?1.75:this.quality==='light'?1:1.35));r.toneMapping=THREE.AgXToneMapping;r.toneMappingExposure=1;r.shadowMap.enabled=true;r.shadowMap.type=THREE.BasicShadowMap;$('viewport').appendChild(r.domElement);await r.init();
  for(const name of ['car','vehicle']){const res=await fetch(`./kernels/${name}.cu`);if(!res.ok)throw Error('Missing CUDA source: '+name);this.sources[name]=await res.text();}
  this.sim=await VehicleSimulation.create(r,this.runtime,this.sources.vehicle,this.track,progress);this.car=await CudaCar.create(r,this.runtime,this.sources.car,{quality:this.quality,poses:this.sim.poses,onProgress:progress});progress('Lighting the atelier and building the proving circuit…');this.stage=new Stage(r,this.car,this.sim,this.quality);this.controls=new OrbitControls(this.stage.camera,r.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.minDistance=.1;this.controls.maxDistance=35;this.controls.maxPolarAngle=Math.PI*.495;this.controls.target.set(0,.55,0);this.controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
  this.input=new DrivingInput(r.domElement,{reset:()=>this.reset(),camera:()=>this.cycleCamera(),pause:()=>this.togglePause(),menu:()=>this.menu(),garage:()=>this.garage(),mute:()=>{this.audio.toggle();$('audio').checked=!this.audio.muted;},lamps:()=>{this.car.lamps.value=1-this.car.lamps.value;}});this.resize=()=>{const w=innerWidth,h=innerHeight;r.setSize(w,h);this.stage.camera.aspect=w/h;this.stage.camera.updateProjectionMatrix();};window.addEventListener('resize',this.resize);this.resize();r.domElement.addEventListener('pointerdown',()=>this.input.focus());this.shot('hero');progress('Compiling the first rendered view…');r.render(this.stage.scene,this.stage.camera);await this.runtime.idle();await this.sim.telemetry();
  this.ready=true;show('loading',false);show('topbar');show('garage');show('stats');$('counts').textContent=`${this.car.partCount} CUDA parts · ${this.car.triangles.toLocaleString()} triangles`;
  this.previousTime=performance.now();this.statsStart=this.previousTime;this.simStart=this.sim.time;this.input.focus();this.frameHandle=requestAnimationFrame(t=>this.frame(t));this.starting=false;window.__AERIS__={app:this,snapshot:()=>({ready:this.ready,mode:this.mode,paused:this.paused,keys:[...this.input.keys],state:Array.from(this.sim.last),stats:{triangles:this.car.triangles,parts:this.car.partCount,readbackBytes:this.runtime.stats.readbackBytes}})};
 }catch(e){console.error(e);show('loading',false);show('title');$('startError').textContent=e.message||String(e);$('start').disabled=false;this.starting=false;await this.dispose();}}
 async frame(now){if(this.lost||!this.ready)return;const frameMs=Math.max(0,now-this.previousTime),delta=Math.min(.08,frameMs/1000);this.previousTime=now;this.frameIntervals??=[];this.frameIntervals.push(frameMs);if(this.frameIntervals.length>120)this.frameIntervals.shift();if(this.busy){this.frameHandle=requestAnimationFrame(t=>this.frame(t));return;}this.busy=true;try{
  const blocked=!$('settings').classList.contains('hidden')||!$('sourceModal').classList.contains('hidden');this.input.enabled=!blocked;let state=this.sim.last,simDt=0;
  if(!this.paused&&!this.photo&&!blocked&&!document.hidden){this.accumulator=Math.min(this.accumulator+delta,8*FIXED_DT);const n=Math.min(8,Math.floor(this.accumulator/FIXED_DT));if(n){let input=this.input.sample();if(this.touring&&this.mode==='drive'){if(input.drive||input.steering||input.handbrake){this.touring=false;toast('Tour ended — you have control');}else input=this.tourInput(state);}this.sim.advance(input,n);state=await this.sim.telemetry();this.accumulator-=n*FIXED_DT;simDt=n*FIXED_DT;}}
  this.stage.update(state,delta);this.audio.update(state,this.mode==='drive'&&!this.paused&&!this.photo&&!blocked);if(this.mode==='garage'||this.photo)this.controls.update();else this.driveCamera(state,delta);this.renderer.render(this.stage.scene,this.stage.camera);this.updateHud(state,simDt);this.frameCount++;
  if(now-this.statsStart>=800){const seconds=(now-this.statsStart)/1000;this.renderRate=this.frameCount/seconds;const times=[...this.frameIntervals].sort((a,b)=>a-b);$('fps').textContent=`${this.renderRate.toFixed(0)} FPS · p95 ${times[Math.floor((times.length-1)*.95)].toFixed(1)} ms`;$('simRate').textContent=`SIM ${((this.sim.time-this.simStart)/seconds).toFixed(2)}× · ${(this.runtime.stats.readbackBytes/1024).toFixed(0)} KiB read`;this.statsStart=now;this.simStart=this.sim.time;this.frameCount=0;}
 }catch(e){this.fail(e);}finally{this.busy=false;if(!this.lost)this.frameHandle=requestAnimationFrame(t=>this.frame(t));}}
 driveCamera(s,dt,instant=false){const c=this.stage.camera,p=new THREE.Vector3(s[0],s[1],s[2]),yaw=s[3],f=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));let target,eye,fov;
 if(this.cameraIndex===0){eye=p.clone().addScaledVector(f,-6.3-Math.min(s[42],70)*.016);eye.y+=2.05;target=p.clone().addScaledVector(f,3.6);target.y+=.58;fov=47+Math.min(s[42],75)*.10;}
 else if(this.cameraIndex===1){eye=p.clone().addScaledVector(f,.78);eye.y+=.97;target=p.clone().addScaledVector(f,35);target.y+=.65;fov=63;}
 else{eye=p.clone().addScaledVector(right,-.345).addScaledVector(f,.075);eye.y+=.846;target=p.clone().addScaledVector(f,35).addScaledVector(right,-.345);target.y+=.79;fov=67;}
 c.position.lerp(eye,instant||this.cameraIndex>0?1:1-Math.exp(-7*dt));c.lookAt(target);c.fov=fov;c.updateProjectionMatrix();}
 shot(name){if(!this.ready&&!this.stage)return;const v=shots[name]||shots.hero,c=this.stage.camera;c.position.set(...v.p);c.fov=v.fov;c.updateProjectionMatrix();this.controls.target.set(...v.t);this.controls.update();}
 async drive(){if(!this.ready)return;this.closePanels();this.photo=false;this.paused=false;show('pauseBanner',false);this.mode='drive';this.controls.enabled=false;this.controls.autoRotate=false;this.sim.reset(false);this.trial.reset();this.accumulator=0;this.stage.setMode('drive');show('garage',false);show('photo',false);show('hud');show('touch');$('modeLabel').textContent='COASTAL / DRIVE';this.driveCamera(this.sim.last,0,true);this.input.clear();this.input.focus();try{await this.audio.start();}catch(e){console.warn('Audio disabled',e);}toast('W / ↑ accelerates · S / ↓ brakes then reverses');}
 tourInput(s){const speed=Math.hypot(s[4],s[6]),road=this.track.road,near=nearestTrack(road,s[0],s[2]);const i=(near.index+Math.max(3,Math.round(speed*.45)))%this.track.count;const target=Math.atan2(road[i*4]-s[0],road[i*4+2]-s[2]);const error=Math.atan2(Math.sin(target-s[3]),Math.cos(target-s[3]));return {drive:Math.max(-.5,Math.min(.65,(14-speed)*.22)),steering:Math.max(-1,Math.min(1,error*2.2)),handbrake:0,shift:0};}
 garage(){this.touring=false;if(!this.ready)return;this.closePanels();this.photo=false;this.paused=false;show('pauseBanner',false);this.mode='garage';this.sim.reset(true);this.controls.enabled=true;this.stage.setMode('garage');show('garage');show('hud',false);show('touch',false);show('photo',false);$('modeLabel').textContent='ATELIER';this.shot('hero');this.input.clear();this.input.focus();}
 reset(){if(!this.ready)return;this.sim.reset(this.mode==='garage');this.trial.reset();this.accumulator=0;this.input.clear();if(this.mode==='drive')this.driveCamera(this.sim.last,0,true);toast('Position reset');}
 togglePause(){if(!this.ready)return;this.paused=!this.paused;this.input.clear();this.accumulator=0;toast(this.paused?'Driving paused':'Driving resumed');$('pauseBtn').textContent=this.paused?'Resume driving':'Pause driving';$('pauseBanner').classList.toggle('hidden',!this.paused);}
 cycleCamera(){if(this.mode!=='drive'||this.photo)return;this.cameraIndex=(this.cameraIndex+1)%3;this.driveCamera(this.sim.last,0,true);toast(['Chase camera','Bonnet camera','Cockpit camera'][this.cameraIndex]);}
 menu(force){if(!this.ready)return;if(force===undefined&&!$('sourceModal').classList.contains('hidden')){show('sourceModal',false);return;}const open=force===undefined?$('settings').classList.contains('hidden'):force;show('settings',open);this.input.enabled=!open;this.input.clear();if(!open)this.input.focus();}
 closePanels(){show('settings',false);show('sourceModal',false);this.input?.clear();}
 photoMode(value){if(!this.ready)return;this.closePanels();this.photo=value;this.controls.enabled=value||this.mode==='garage';show('photo',value);show('garage',!value&&this.mode==='garage');show('hud',!value&&this.mode==='drive');show('touch',!value&&this.mode==='drive');this.input.clear();if(value){const s=this.sim.last;this.controls.target.set(s[0],.6,s[2]);this.controls.update();$('fov').value=this.stage.camera.fov;}else if(this.mode==='drive')this.driveCamera(this.sim.last,0,true);else this.shot('hero');}
 updateHud(s,dt){const t=this.mode==='drive'?this.trial.update(s[0],s[2],dt):null;const now=performance.now();if(now-(this.hudUpdated||0)<100)return;this.hudUpdated=now;$('gear').textContent=s[9]<0?'R':Math.round(s[9]);$('speed').textContent=String(Math.round(Math.hypot(s[4],s[6])*3.6)).padStart(3,'0');$('rpmText').textContent=`${Math.round(s[8])} RPM`;$('rpmBar').style.width=`${Math.max(0,Math.min(100,s[8]/8200*100))}%`;$('assists').textContent=s[23]>.1?'HANDBRAKE':s[47]>.5?'SLIP':s[44]>.5?'TCS ACTIVE':s[45]>.5?'ABS':'TCS / ESC';if(this.mode!=='drive')return;$('lapTime').textContent=fmt(t.time);$('lapInfo').textContent=`Lap ${t.lap} · ${t.sector} / 4 sectors${t.invalid?' · OFF TRACK':''}`;$('bestTime').textContent=`Best ${fmt(t.best)}`;const ctx=$('map').getContext('2d'),cv=$('map'),mx=x=>x/3.3+100,mz=z=>110-z/3.3;ctx.clearRect(0,0,cv.width,cv.height);if(!this.mapPath){this.mapPath=new Path2D();for(let i=0;i<this.track.count;i++){const x=mx(this.track.road[i*4]),z=mz(this.track.road[i*4+2]);if(!i)this.mapPath.moveTo(x,z);else this.mapPath.lineTo(x,z);}this.mapPath.closePath();}ctx.strokeStyle='#bfd2dc80';ctx.lineWidth=3;ctx.stroke(this.mapPath);ctx.fillStyle=t.invalid?'#ff7563':'#f2c89f';ctx.save();ctx.translate(mx(s[0]),mz(s[2]));ctx.rotate(s[3]);ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(4,5);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.restore();}
 async capture(){if(!this.ready)return;this.renderer.render(this.stage.scene,this.stage.camera);await this.runtime.idle();this.renderer.domElement.toBlob(b=>{if(b)download(`aeris-${Date.now()}.png`,b,'image/png');else toast('PNG capture was unavailable');},'image/png');}
 setup(){return {format:'aeris-setup',version:1,paint:this.paint,wheels:$('wheelColor').value,light:$('light').value,exposure:Number($('exposure').value),parameters:{...this.sim.parameters}};}
 importSetup(value){if(value?.format!=='aeris-setup'||value.version!==1||!Object.hasOwn(PAINTS,value.paint))throw Error('Not an AERIS setup');const p=value.parameters;if(!p||!['automatic','tractionControl','stabilityControl'].every(k=>[0,1].includes(p[k]))||!Number.isFinite(p.wetness)||p.wetness<0||p.wetness>1)throw Error('Invalid driving setup');if(!['day','golden','night'].includes(value.light)||!Number.isFinite(value.exposure)||value.exposure<.5||value.exposure>1.8||!/^#[0-9a-fA-F]{6}$/.test(value.wheels))throw Error('Invalid appearance');this.sim.parameters={...p};this.paint=value.paint;this.car.setPaint(value.paint);this.car.wheels.value.set(value.wheels);this.stage.setLighting(value.light);this.renderer.toneMappingExposure=value.exposure;$('wheelColor').value=value.wheels;$('light').value=value.light;$('exposure').value=value.exposure;$('wetness').value=p.wetness;$('wetValue').value=Math.round(p.wetness*100)+'%';$('automatic').checked=!!p.automatic;$('tc').checked=!!p.tractionControl;$('esc').checked=!!p.stabilityControl;selectPaint(value.paint);toast('Setup imported');}
 fail(e){if(this.lost)return;this.lost=true;this.input?.clear();console.error(e);$('fatalText').textContent=e?.message||String(e);show('fatal');}
 async dispose(){cancelAnimationFrame(this.frameHandle);this.ready=false;this.input?.dispose();this.controls?.dispose();this.audio.dispose();try{await this.runtime?.idle();}catch{}this.stage?.dispose();this.car?.dispose();this.sim?.dispose();this.renderer?.dispose();this.renderer?.domElement.remove();this.runtime?.dispose();if(this.resize)window.removeEventListener('resize',this.resize);}
}
const app=new AerisApp();function selectPaint(name){app.paint=name;app.car?.setPaint(name);$('paintName').textContent=name[0].toUpperCase()+name.slice(1)+' metallic';for(const b of $('paints').children)b.classList.toggle('active',b.dataset.paint===name);}
for(const [name,c]of Object.entries(PAINTS)){const b=document.createElement('button');b.className='swatch';b.title=name;b.setAttribute('aria-label',name+' paint');b.style.background=c;b.dataset.paint=name;b.onclick=()=>selectPaint(name);$('paints').appendChild(b);}selectPaint('petrol');
$('start').onclick=()=>app.start();$('driveBtn').onclick=()=>app.drive();$('garageBtn').onclick=()=>app.garage();$('brandHome').onclick=e=>{e.preventDefault();app.garage();};$('menuBtn').onclick=()=>app.menu();$('closeMenu').onclick=()=>app.menu(false);$('photoBtn').onclick=()=>app.photoMode(!app.photo);$('exitPhoto').onclick=()=>app.photoMode(false);$('captureBtn').onclick=()=>app.capture();$('fov').oninput=e=>{app.stage.camera.fov=Number(e.target.value);app.stage.camera.updateProjectionMatrix();};for(const b of document.querySelectorAll('[data-shot]'))b.onclick=()=>app.shot(b.dataset.shot);
$('turntable').onclick=()=>{app.controls.autoRotate=!app.controls.autoRotate;app.controls.autoRotateSpeed=.65;};$('wheelColor').onchange=e=>app.car.wheels.value.set(e.target.value);$('light').onchange=e=>app.stage.setLighting(e.target.value);$('exposure').oninput=e=>app.renderer.toneMappingExposure=Number(e.target.value);$('debug').onchange=e=>app.car.mode.value=Number(e.target.value);$('wetness').oninput=e=>{app.sim.parameters.wetness=Number(e.target.value);$('wetValue').value=Math.round(Number(e.target.value)*100)+'%';};for(const [id,key]of [['tc','tractionControl'],['esc','stabilityControl'],['automatic','automatic']])$(id).onchange=e=>app.sim.parameters[key]=e.target.checked?1:0;$('audio').onchange=e=>app.audio.muted=!e.target.checked;$('resetBtn').onclick=()=>app.reset();$('pauseBtn').onclick=()=>app.togglePause();$('sourceBtn').onclick=()=>{show('sourceModal');$('sourceText').textContent=app.sources[$('sourceSelect').value];};$('sourceSelect').onchange=e=>$('sourceText').textContent=app.sources[e.target.value];$('closeSource').onclick=()=>show('sourceModal',false);$('exportBtn').onclick=()=>download('aeris-setup.json',JSON.stringify(app.setup(),null,2));$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>64000)throw Error('Setup file is too large');app.importSetup(JSON.parse(await f.text()));}catch(e){toast(e.message);}e.target.value='';};$('diagnosticBtn').onclick=async()=>{const b=$('diagnosticBtn');b.disabled=true;try{const {runDiagnostics}=await import('./diagnostics.js');const report=await runDiagnostics(app.runtime,app.sources,app.track);download('aeris-gpu-checks.json',JSON.stringify(report,null,2));toast(`${report.passed}/${report.results.length} device checks passed`);}catch(e){toast(e.message);}finally{b.disabled=false;}};
for(const b of document.querySelectorAll('[data-touch]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);app.input?.setTouch(e.pointerId,b.dataset.touch,true);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,e=>app.input?.setTouch(e.pointerId,b.dataset.touch,false));}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&app.ready&&app.mode==='drive'){if(!app.paused)app.togglePause();}});window.addEventListener('pagehide',()=>{app.input?.clear();app.audio.context?.suspend();});

$('resumeBtn').onclick=()=>{if(app.paused)app.togglePause();app.input.focus();};
$('recordBtn').onclick=()=>{
 if(!app.ready||app.recording)return;
 const canvas=app.renderer.domElement,stream=canvas.captureStream(30);
 const mimeType=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));
 if(!mimeType){stream.getTracks().forEach(t=>t.stop());toast('Video recording is unavailable in this browser');return;}
 const chunks=[],rec=new MediaRecorder(stream,{mimeType,videoBitsPerSecond:14000000});app.recording=true;$('recordBtn').disabled=true;
 const start=performance.now();const timer=setInterval(()=>{$('recordBtn').textContent=`REC ${Math.max(0,60-Math.floor((performance.now()-start)/1000))}s`;},250);
 const finish=()=>{clearInterval(timer);stream.getTracks().forEach(t=>t.stop());app.recording=false;$('recordBtn').disabled=false;$('recordBtn').textContent='Record 60s';};
 rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{finish();download('aeris-showcase.webm',new Blob(chunks,{type:mimeType}));toast('Live showcase saved');};rec.onerror=()=>{finish();toast('Recording failed');};rec.start(1000);setTimeout(()=>{if(rec.state==='recording')rec.stop();},60000);toast('Recording live for 60 seconds. Keep this window visible.');
};

$('tourBtn').onclick=async()=>{await app.drive();app.touring=true;toast('Guided tour — use WASD to take over');};
