import * as THREE from 'three/webgpu';
import {Fn,If,float,int,uint,vec2,vec3,vec4,vertexIndex,uniform,texture,varying,transformNormalToView,positionView,dFdx,dFdy,cross,dot,normalize,max,sin,cos,mix,clamp,smoothstep,reflect,pow,acos,atan,cameraWorldMatrix,cameraViewMatrix} from 'three/tsl';
import {createSharedFloat4} from '../vendor/cuda-webshader/src/runtime/three-bridge.js';
export const MATERIAL_NAMES=['Metallic clearcoat','Carbon fibre','Tyre compound','Forged alloy','Brake rotors','Calipers','Glazing','Satin trim','Headlamps','Tail / brake lamps','Leather','Stitching','Instruments','Chrome','Lamp liners','Amber','Signature','Mirrors'];
export const PAINTS={petrol:'#064d5f',carmine:'#921226',glacier:'#bac8d0',cobalt:'#164ba1',champagne:'#aa8c60',graphite:'#242832',papaya:'#ce450a'};
function poseVector(p,tag,poses,normal=false){const i=uint(tag).mul(4),a=poses.node.element(i).xyz,b=poses.node.element(i.add(1)).xyz,c=poses.node.element(i.add(2)).xyz,translation=poses.node.element(i.add(3)).xyz;const q=a.mul(p.x).add(b.mul(p.y)).add(c.mul(p.z));return normal?q:q.add(translation);}
export class CudaCar{
 static async create(renderer,runtime,source,{quality='balanced',poses,onProgress=()=>{}}){const car=new CudaCar(renderer,runtime,poses);try{await car.build(source,quality,onProgress);return car;}catch(e){car.dispose();throw e;}}
 constructor(renderer,runtime,poses){this.renderer=renderer;this.runtime=runtime;this.poses=poses;this.group=new THREE.Group();this.group.name='AERIS R · CUDA authored';this.owned=[];this.shared=[];this.textures=[];this.materials=[];this.meshes=[];this.kernels={};this.paint=uniform(new THREE.Color(PAINTS.petrol));this.lamps=uniform(1);this.brake=uniform(0);this.wheels=uniform(new THREE.Color('#aeb7c1'));this.mode=uniform(0);this.envNode=texture(new THREE.DataTexture(new Uint8Array([80,90,100,255]),1,1));this.envNode.value.needsUpdate=true;this.sunDirection=uniform(new THREE.Vector3(-12,18,9).normalize());this.sunColor=uniform(new THREE.Color('#fff0db'));this.sunStrength=uniform(1.8);}
 async build(source,quality,onProgress){const rt=this.runtime;for(const entry of ['describeCar','sampleCar','buildCar','bakeSurface']){onProgress('Car kernel / '+entry);this.kernels[entry]=await rt.kernel(source,{entry,workgroupSize:[128,1,1]});}
 const make=(data,label)=>{const r=rt.createBuffer(data,{label});this.owned.push(r);return r;};this.parts=make(512*160,'CUDA CAD descriptors');const countBuffer=make(4,'CAD count');rt.batch().dispatch(this.kernels.describeCar.bind({parts:this.parts,count:countBuffer},{}),[1]).submit();const count=(await rt.read(countBuffer,Uint32Array))[0];if(count<1||count>512)throw Error('Invalid generated car layout');this.partCount=count;this.descriptors=await rt.read(this.parts,Float32Array,count*160);
 const factor=quality==='high'?1.5:quality==='light'?.60:1,jobs=new Float32Array(count*4);this.drawGroups=[];let total=0,samples=0;
 for(let mat=0;mat<MATERIAL_NAMES.length;mat++){const start=total;for(let id=0;id<count;id++){const o=id*40;if(this.descriptors[o+1]!==mat)continue;const nu=Math.max(3,Math.round(this.descriptors[o+3]*factor)),nv=Math.max(2,Math.round(this.descriptors[o+7]*factor));jobs.set([total,nu,nv,samples],id*4);total+=nu*nv*6;samples+=(nu+1)*(nv+1);}if(total>start)this.drawGroups.push({material:mat,start,count:total-start});}
 if(total*16>rt.device.limits.maxStorageBufferBindingSize)throw Error('Mesh exceeds this GPU storage limit. Use Light.');this.vertexCount=total;this.triangles=total/3;this.bytes=total*48;this.jobs=make(jobs,'Material-grouped dispatch layout');const sampleBuffer=make(samples*16,'Parametric surface samples');
 for(const key of ['positions','normals','uvMeta']){this[key]=createSharedFloat4(this.renderer,rt,new Float32Array(total*4),{label:'CUDA car '+key});this.shared.push(this[key]);}
 onProgress(`Generating ${count} components · ${this.triangles.toLocaleString()} triangles`);rt.batch().dispatch(this.kernels.sampleCar.bind({parts:this.parts,jobs:this.jobs,samples:sampleBuffer},{partCount:count}),[count]).dispatch(this.kernels.buildCar.bind({parts:this.parts,jobs:this.jobs,samples:sampleBuffer,positions:this.positions.resource,normals:this.normals.resource,uvMeta:this.uvMeta.resource},{partCount:count}),[count]).submit();await this.bake(quality,onProgress);this.createMaterials();
 for(const group of this.drawGroups){const m=this.materials[group.material],g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(new Float32Array(group.count*3),3));g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(group.count*2),2));const ix=vertexIndex.add(group.start),p=this.positions.node.element(ix),n=this.normals.node.element(ix),meta=this.uvMeta.node.element(ix),uvn=varying(meta.xy),nn=varying(transformNormalToView(poseVector(n.xyz,p.w,this.poses,true)));m.positionNode=poseVector(p.xyz,p.w,this.poses);m.normalNode=nn;m.clearcoatNormalNode=nn;
 const sid={0:5,1:0,2:1,4:4,10:2}[group.material];if(sid!==undefined){const maps=this.surfaces[sid],coord=uvn.mul(group.material===1?2:1),nc=texture(maps.normal,coord),map=nc.rgb.mul(2).sub(1);m.colorNode=texture(maps.color,coord).rgb.mul(m.color);m.roughnessNode=nc.a;
 // Default look uses smooth CUDA geometric normals. Normal RGB is baked for
 // inspection/extensions; its alpha roughness channel is consumed here.
 m.normalNode=nn;}
 if(group.material===0){m.colorNode=texture(this.surfaces[5].color,uvn.mul(2)).rgb.mul(this.paint);m.roughnessNode=texture(this.surfaces[5].normal,uvn.mul(2)).a.mul(.8);}
 if(group.material===3)m.colorNode=this.wheels;
 if(group.material===4){const holes=sin(uvn.x.mul(48*Math.PI)).abs().lessThan(.18).and(sin(uvn.y.mul(8*Math.PI)).abs().lessThan(.2)).and(uvn.y.greaterThan(.55));m.colorNode=holes.select(vec3(.008),vec3(.31,.32,.33));}
 if(group.material===8)m.emissiveNode=vec3(1,.9,.76).mul(this.lamps.mul(2.3).add(.05));if(group.material===9)m.emissiveNode=vec3(1,.014,.003).mul(this.brake.mul(3.5).add(.45));
 if(group.material===12)m.emissiveNode=sin(uvn.x.mul(48)).greaterThan(.4).select(vec3(.12,.36,.43),vec3(.006,.012,.02));
 // View modes do not alter physics or meshes.
 const colour=m.colorNode||vec3(m.color);m.colorNode=this.mode.equal(1).select(vec3(.35),this.mode.equal(2).select(normalize(nn).mul(.5).add(.5),colour));
 const baseNode=m.colorNode,roughNode=m.roughnessNode||float(m.roughness),metal=float(m.metalness||0),emission=m.emissiveNode||vec3(0),coat=float(m.clearcoat||0);
 // Explicit compact GGX + equirectangular image-based lighting. This avoids the
 // huge stock multi-light/CubeUV graph on software Vulkan; it is also used in
 // the shipping browser, not a test-only substitute.
 m.fragmentNode=Fn(()=>{const N=normalize(nn),V=normalize(positionView.negate()),nv=max(dot(N,V),.001),L=normalize(cameraViewMatrix.mul(vec4(this.sunDirection,0)).xyz),H=normalize(L.add(V)),nl=max(dot(N,L),0),nh=max(dot(N,H),0),hv=max(dot(H,V),0),rough=clamp(roughNode,.055,1),a=rough.mul(rough),a2=a.mul(a),den=nh.mul(nh).mul(a2.sub(1)).add(1),D=a2.div(den.mul(den).mul(Math.PI).add(.00001)),k=rough.add(1).pow(2).div(8),G=nv.div(nv.mul(float(1).sub(k)).add(k)).mul(nl.div(nl.mul(float(1).sub(k)).add(k).add(.001))),f0=mix(vec3(.04),baseNode,metal),F=f0.add(vec3(1).sub(f0).mul(pow(float(1).sub(hv),5))),spec=F.mul(D).mul(G).div(nv.mul(nl).mul(4).add(.001)),diff=baseNode.mul(float(1).sub(metal)).mul(vec3(1).sub(F)).div(Math.PI);
 const ray=normalize(cameraWorldMatrix.mul(vec4(reflect(V.negate(),N),0)).xyz),euv=vec2(atan(ray.z,ray.x.negate()).div(2*Math.PI).add(.5),acos(clamp(ray.y,-.99999,.99999)).div(Math.PI)),env=this.envNode.sample(euv).rgb,evF=f0.add(vec3(1).sub(f0).mul(pow(float(1).sub(nv),5))),reflected=env.mul(evF).mul(float(1).sub(rough.mul(.55))),ambient=baseNode.mul(vec3(.16,.18,.20)).mul(float(1).sub(metal));
 const result=diff.add(spec).mul(this.sunColor).mul(this.sunStrength).mul(nl).add(reflected).add(ambient).add(env.mul(coat).mul(.024)).add(emission);const debug=this.mode.equal(1).select(vec3(.35).mul(nl.mul(.6).add(.3)),this.mode.equal(2).select(N.mul(.5).add(.5),result));return vec4(debug,group.material===6?.28:1);})();
 if(this.quality!=='light'){m.fragmentNode=null;}
 const mesh=new THREE.Mesh(g,m);mesh.name=MATERIAL_NAMES[group.material];mesh.frustumCulled=false;mesh.castShadow=group.material!==6;mesh.receiveShadow=true;this.meshes.push(mesh);this.group.add(mesh);}
 await rt.idle();return this;
 }
 async bake(quality,onProgress){const rt=this.runtime,w=quality==='high'?512:256;this.surfaces=[];if(!rt.device.features.has('float32-filterable'))throw Error('This demo requires float32-filterable WebGPU textures. Try a desktop GPU/browser.');for(let kind=0;kind<6;kind++){onProgress('CUDA material bake '+(kind+1)+'/6');const a=rt.createBuffer(w*w*16),b=rt.createBuffer(w*w*16);rt.batch().dispatch(this.kernels.bakeSurface.bind({colorMap:a,normalRough:b},{width:w,kind}),[Math.ceil(w*w/128)]).submit();const make=()=>{const t=new THREE.DataTexture(new Float32Array(w*w*4),w,w,THREE.RGBAFormat,THREE.FloatType);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;t.needsUpdate=true;this.renderer.initTexture(t);this.textures.push(t);return t;};const color=make(),normal=make(),e=rt.device.createCommandEncoder();e.copyBufferToTexture({buffer:a.gpuBuffer,bytesPerRow:w*16},{texture:this.renderer.backend.get(color).texture},[w,w]);e.copyBufferToTexture({buffer:b.gpuBuffer,bytesPerRow:w*16},{texture:this.renderer.backend.get(normal).texture},[w,w]);rt.device.queue.submit([e.finish()]);this.renderer.backend.generateMipmaps(color);this.renderer.backend.generateMipmaps(normal);await rt.idle();rt.destroyBuffer(a);rt.destroyBuffer(b);this.surfaces.push({color,normal});}}
 createMaterials(){const p=(color,metalness,roughness,more={})=>new THREE.MeshPhysicalNodeMaterial({color,metalness,roughness,side:THREE.DoubleSide,fog:false,...more});this.materials=[p(PAINTS.petrol,.57,.18,{clearcoat:1,clearcoatRoughness:.065}),p('#b3b8ba',.32,.28,{clearcoat:.9,clearcoatRoughness:.15}),p('#aaaaaa',0,.85),p('#aeb7c1',1,.23),p('#93979b',.95,.4),p('#d83b0a',.45,.26,{clearcoat:1}),p('#8ba6a3',0,.065,{transmission:0,thickness:.015,ior:1.5,transparent:true,opacity:.32,depthWrite:false,clearcoat:1,clearcoatRoughness:.045}),p('#14191e',.15,.38),p('#eef4fa',.1,.12),p('#560805',.2,.13),p('#a6a09b',0,.65),p('#bc9e7d',0,.70),p('#081119',.15,.2),p('#ced5d8',1,.13),p('#03070a',.25,.13,{clearcoat:1}),p('#db7816',.2,.2),p('#b8bdc0',.95,.24),p('#b4c9d4',1,.015)];this.materials[6].forceSinglePass=true;}
 setPaint(name){if(!Object.hasOwn(PAINTS,name))throw Error('Unknown paint');this.paint.value.set(PAINTS[name]);}
 dispose(){for(const m of this.meshes)m.geometry.dispose();for(const m of this.materials)m.dispose();for(const t of this.textures)t.dispose();for(const s of this.shared)s.dispose();for(const r of this.owned)this.runtime.destroyBuffer(r);this.group.clear();this.owned=[];}
}
