const KEY_CODES={w:'KeyW',s:'KeyS',a:'KeyA',d:'KeyD',' ':'Space',r:'KeyR',c:'KeyC',p:'KeyP',g:'KeyG',m:'KeyM',q:'KeyQ',e:'KeyE',h:'KeyH',escape:'Escape',arrowup:'ArrowUp',arrowdown:'ArrowDown',arrowleft:'ArrowLeft',arrowright:'ArrowRight'};
export class DrivingInput{
 constructor(canvas,callbacks={},win=window){this.canvas=canvas;this.callbacks=callbacks;this.win=win;this.keys=new Set();this.touches=new Map();this.shift=0;this.previousPad=new Map();this.enabled=true;this.onDown=e=>this.key(e,true);this.onUp=e=>this.key(e,false);this.onBlur=()=>this.clear();win.addEventListener('keydown',this.onDown);win.addEventListener('keyup',this.onUp);win.addEventListener('blur',this.onBlur);this.onHide=()=>{if(win.document?.hidden)this.clear();};win.document?.addEventListener('visibilitychange',this.onHide);canvas.tabIndex=0;}
 key(e,down){const code=e.code||KEY_CODES[String(e.key).toLowerCase()]||e.key;if(!down){this.keys.delete(code);return;}const t=e.target;if(t?.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(t?.tagName))return;if(!this.enabled){if(code==='Escape'&&!e.repeat){e.preventDefault?.();this.callbacks.menu?.();}return;}const used=['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyR','KeyC','KeyP','KeyG','KeyM','KeyQ','KeyE','KeyH','Escape'];if(!used.includes(code))return;e.preventDefault?.();this.keys.add(code);if(e.repeat)return;const action={KeyR:'reset',KeyC:'camera',KeyP:'pause',Escape:'menu',KeyG:'garage',KeyM:'mute',KeyH:'lamps'}[code];if(action)this.callbacks[action]?.();if(code==='KeyQ')this.shift=-1;if(code==='KeyE')this.shift=1;}
 setTouch(id,action,down){if(down)this.touches.set(id,action);else this.touches.delete(id);}
 sample(gamepads=this.win.navigator?.getGamepads?.()||[]){if(!this.enabled)return {drive:0,brake:0,steering:0,handbrake:0,shift:0};const active=action=>[...this.touches.values()].includes(action),key=(...k)=>k.some(x=>this.keys.has(x));let drive=(key('KeyW','ArrowUp')||active('throttle')?1:0)-(key('KeyS','ArrowDown')||active('brake')?1:0),steering=(key('KeyD','ArrowRight')||active('right')?1:0)-(key('KeyA','ArrowLeft')||active('left')?1:0),handbrake=key('Space')||active('handbrake')?1:0;
 for(const pad of gamepads){if(!pad?.connected)continue;const axis=pad.axes[0]||0;if(Math.abs(axis)>.10)steering=Math.sign(axis)*(Math.abs(axis)-.10)/.90;const throttle=pad.buttons[7]?.value||0,brake=pad.buttons[6]?.value||0;if(throttle+brake>.04)drive=throttle-brake;handbrake=Math.max(handbrake,pad.buttons[0]?.value||0);const c=pad.buttons[3]?.pressed||false;if(c&&!this.previousPad.get(pad.index))this.callbacks.camera?.();this.previousPad.set(pad.index,c);break;}
 // +Z is forward: driver-right is -X (negative yaw). Convert every input source once.
 steering=-steering;const shift=this.shift;this.shift=0;return {drive,brake:0,steering,handbrake,shift};}
 focus(){this.canvas.focus({preventScroll:true});}
 clear(){this.keys.clear();this.touches.clear();this.shift=0;}
 dispose(){this.win.removeEventListener('keydown',this.onDown);this.win.removeEventListener('keyup',this.onUp);this.win.removeEventListener('blur',this.onBlur);this.win.document?.removeEventListener('visibilitychange',this.onHide);this.clear();}
}
