import {createSharedFloat4} from '../vendor/cuda-webshader/src/runtime/three-bridge.js';
export const FIXED_DT=1/120;
export const VEHICLE_ENTRIES=['resetVehicle','stepVehicle','tireForces','integrateVehicle','buildPose','updateEffects'];
export function validateInput(input){const v={drive:0,brake:0,steering:0,handbrake:0,shift:0,...input};for(const k of ['drive','brake','steering','handbrake'])if(!Number.isFinite(v[k])||Math.abs(v[k])>1)throw RangeError('Invalid '+k);if(![-1,0,1].includes(v.shift))throw RangeError('Invalid shift');return v;}
export function bindDriving(k,r,c){const {state,road,obstacles,forces,marks,poses,smoke,smokeVelocity}=r;return {
 init:k.resetVehicle.bind({state,smoke,smokeVelocity,marks},{smokeCount:c.smokeCount,markCount:c.markCount,x:0,z:0,yaw:0}),
 step:k.stepVehicle.bind({state,road},{roadCount:c.roadCount,dt:FIXED_DT,drive:0,brake:0,steering:0,handbrake:0,automatic:1,shift:0,wetness:0,showroom:1}),
 tires:k.tireForces.bind({state,forces},{dt:FIXED_DT,tractionControl:1}),
 integrate:k.integrateVehicle.bind({state,forces,obstacles,marks},{obstacleCount:c.obstacleCount,markCount:c.markCount,dt:FIXED_DT,stabilityControl:1}),
 pose:k.buildPose.bind({state,poses},{}),
 effects:k.updateEffects.bind({state,smoke,smokeVelocity},{count:c.smokeCount,dt:FIXED_DT})};}
export function recordDriving(batch,b,input,parameters,substeps){const {tractionControl,stabilityControl,...p}=parameters;b.step.setScalars({...input,...p});b.tires.setScalars({tractionControl});b.integrate.setScalars({stabilityControl});for(let i=0;i<substeps;i++){b.step.setScalars({shift:i===0?input.shift:0});batch.dispatch(b.step,[1]).dispatch(b.tires,[1]).dispatch(b.integrate,[1]);}return batch;}
export class VehicleSimulation{
 static async create(renderer,runtime,source,track,onProgress=()=>{}){const s=new VehicleSimulation(renderer,runtime,track);try{for(const name of VEHICLE_ENTRIES){onProgress('Driving kernel / '+name);s.kernels[name]=await runtime.kernel(source,{entry:name,workgroupSize:[name==='stepVehicle'||name==='integrateVehicle'?1:128,1,1]});}s.bind();s.reset(true);return s;}catch(e){s.dispose();throw e;}}
 constructor(renderer,runtime,track){this.runtime=runtime;this.track=track;this.kernels={};this.owned=[];this.shared=[];this.smokeCount=2048;this.markCount=8192;const shared=(n,label)=>{const v=createSharedFloat4(renderer,runtime,new Float32Array(n*4),{label});this.shared.push(v);return v;};this.state=shared(16,'CUDA vehicle state');this.poses=shared(40,'CUDA animation transforms');this.smoke=shared(this.smokeCount,'CUDA tyre smoke');this.marks=shared(this.markCount*2,'CUDA skid history');const make=(data,label)=>{const v=runtime.createBuffer(data,{label});this.owned.push(v);return v;};this.road=make(track.road,'Track surface classification');this.obstacles=make(track.obstacles,'Visible obstacle collisions');this.forces=make(64,'Independent tyre forces');this.smokeVelocity=make(this.smokeCount*16,'Smoke velocity');this.parameters={automatic:1,tractionControl:1,stabilityControl:1,wetness:0};this.last=new Float32Array(64);this.time=0;this.steps=0;this.showroom=true;}
 bind(){this.b=bindDriving(this.kernels,{state:this.state.resource,road:this.road,obstacles:this.obstacles,forces:this.forces,marks:this.marks.resource,poses:this.poses.resource,smoke:this.smoke.resource,smokeVelocity:this.smokeVelocity},{roadCount:this.track.count,obstacleCount:this.track.obstacles.length/4,smokeCount:this.smokeCount,markCount:this.markCount});}
 reset(showroom=this.showroom){this.showroom=showroom;const p=showroom?{x:0,z:0,yaw:0}:this.track.spawn;this.runtime.batch().dispatch(this.b.init.setScalars(p),[Math.ceil(Math.max(this.markCount*2,this.smokeCount)/128)]).dispatch(this.b.pose,[1]).submit();this.time=0;this.steps=0;this.last.fill(0);this.last.set([p.x,.009,p.z,p.yaw]);this.last[8]=950;this.last[9]=1;}
 advance(input={},substeps=2){if(!Number.isInteger(substeps)||substeps<1||substeps>8)throw RangeError('1..8 fixed substeps');const v=validateInput(input),p=this.parameters;for(const k of ['automatic','tractionControl','stabilityControl'])if(![0,1].includes(p[k]))throw RangeError(k);if(!Number.isFinite(p.wetness)||p.wetness<0||p.wetness>1)throw RangeError('wetness');const batch=this.runtime.batch({label:'CUDA ordered four-contact dynamics'});recordDriving(batch,this.b,v,{...p,showroom:this.showroom?1:0},substeps);batch.dispatch(this.b.pose,[1]).dispatch(this.b.effects.setScalars({dt:substeps*FIXED_DT}),[Math.ceil(this.smokeCount/128)]).submit();this.time+=substeps*FIXED_DT;this.steps+=substeps;}
 async telemetry(){this.last=await this.runtime.read(this.state.resource,Float32Array);return this.last;}
 dispose(){for(const r of this.owned)this.runtime.destroyBuffer(r);for(const s of this.shared)s.dispose();this.owned=[];this.shared=[];}
}
