import * as THREE from 'three/webgpu';
import {texture,positionWorld,positionLocal,vec2,vec3,vec4,float,uniform,instanceIndex,sin,cos,uv,smoothstep,max,mix,clamp} from 'three/tsl';
import {trackPoint} from './track.js';import {makeEnvironment} from './environment.js';
function ribbon(width,offset=0,height=0,n=1024){const p=[],uvs=[];for(let i=0;i<n;i++)for(const [j,side]of [[i,-1],[i,1],[i+1,1],[i,-1],[i+1,1],[i+1,-1]]){const t=j/n*Math.PI*2,a=trackPoint(t),b=trackPoint(t+.0001),dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz),off=offset+side*width/2;p.push(a.x+dz/l*off,height,a.z-dx/l*off);uvs.push(j/n*180,side*.5+.5);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.computeVertexNormals();return g;}
export class Stage{
 constructor(renderer,car,sim,quality='balanced'){this.renderer=renderer;this.car=car;this.sim=sim;this.quality=quality;this.resources=[];this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(42,1,.045,2800);this.camera.position.set(4.7,1.85,6.3);this.camera.lookAt(0,.55,0);this.scene.add(car.group);this.studio=new THREE.Group();this.world=new THREE.Group();this.scene.add(this.studio,this.world);this.env={studio:makeEnvironment(),day:makeEnvironment('day'),golden:makeEnvironment('golden'),night:makeEnvironment('night')};this.time=uniform(0);this.wet=uniform(0);this.mode='garage';this.lightMode='golden';this.scratch=new THREE.Vector3();
 this.sun=new THREE.DirectionalLight('#fff0db',1.8);this.sun.position.set(-8,12,7);this.sun.castShadow=true;this.sun.shadow.mapSize.setScalar(quality==='high'?4096:quality==='light'?1024:2048);this.sun.shadow.bias=-.0002;this.sun.shadow.normalBias=.012;Object.assign(this.sun.shadow.camera,{left:-9,right:9,bottom:-9,top:9,near:.1,far:70});this.scene.add(this.sun,this.sun.target);this.ambient=new THREE.HemisphereLight('#c4d7ed','#72695c',.45);this.scene.add(this.ambient);
 this.headlights=[];for(const x of [-.68,.68]){const l=new THREE.SpotLight('#dceeff',0,90,.24,.7,2);l.position.set(x,.59,2);l.target.position.set(x,.15,25);l.visible=false;this.scene.add(l,l.target);this.headlights.push(l);}
 this.makeStudio();this.makeWorld();this.makeEffects();this.setMode('garage');}
 own(x){this.resources.push(x);return x;}
 add(parent,g,m,p=[0,0,0]){const mesh=new THREE.Mesh(this.own(g),m);mesh.position.set(...p);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 material(c,r=.7,metal=0){return this.own(new THREE.MeshLambertNodeMaterial({color:c}));}
 makeStudio(){const floorMat=this.material('#6d747b',.34,.20);floorMat.color.set('#444b52');const floor=this.add(this.studio,new THREE.PlaneGeometry(160,160),floorMat,[0,-.007,0]);floor.rotation.x=-Math.PI/2;
 const vertices=[];for(let x=0;x<2;x++)for(let i=0;i<=32;i++){const a=i/32*Math.PI/2;vertices.push((x-.5)*90,10-10*Math.cos(a),-12-10*Math.sin(a));}const indices=[];for(let i=0;i<32;i++)indices.push(i,i+33,i+34,i,i+34,i+1);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();this.add(this.studio,g,this.material('#454d55',.9));this.add(this.studio,new THREE.PlaneGeometry(90,40),this.material('#454d55',.9),[0,30,-22]);
 const light=this.own(new THREE.MeshBasicNodeMaterial({color:'#e9eff4'}));for(const s of [-1,1])for(const z of [-3,2,7])this.add(this.studio,new THREE.BoxGeometry(.035,5,.7),light,[s*10,2.5,z]);
 const ring=this.add(this.studio,new THREE.RingGeometry(4.15,4.165,160),this.material('#737e87',.6),[0,.002,0]);ring.rotation.x=-Math.PI/2;ring.castShadow=false;
 }
 makeWorld(){const track=this.sim.track;
 const land=this.material('#74725a',.99);land.colorNode=texture(this.car.surfaces[3].color,uv().mul(250)).rgb.mul(vec3(2.9,2.9,1.85));const ground=this.add(this.world,new THREE.PlaneGeometry(4200,4200),land,[-650,-.045,0]);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
 const asphalt=this.material('#32373b',.88);asphalt.colorNode=texture(this.car.surfaces[3].color,vec2(uv().x.mul(3),uv().y.mul(5))).rgb.mul(float(.70).sub(this.wet.mul(.20)));asphalt.roughnessNode=float(.89).sub(this.wet.mul(.52));this.add(this.world,ribbon(15),asphalt).castShadow=false;
 const white=this.material('#d3d4c8',.84);for(const s of [-1,1]){const shoulder=this.add(this.world,ribbon(.50,s*7.77,.009),this.material('#9d998e'));shoulder.castShadow=false;this.add(this.world,ribbon(.11,s*7.13,.017),white).castShadow=false;const kerb=this.material('#ba2920',.7);kerb.colorNode=sin(uv().x.mul(Math.PI)).greaterThan(0).select(vec3(.43,.026,.018),vec3(.68,.66,.59));this.add(this.world,ribbon(.55,s*8.12,.028),kerb).castShadow=false;const rail=this.material('#838b92',.32,.8);this.add(this.world,ribbon(.12,s*11.65,.65),rail);this.add(this.world,ribbon(.06,s*11.65,.90),rail);}
 const dashed=this.material('#c0bca9',.8);dashed.transparent=true;dashed.opacityNode=sin(uv().x.mul(Math.PI*.5)).greaterThan(.15).select(1,0);this.add(this.world,ribbon(.10,0,.02),dashed).castShadow=false;
 const check=this.material('#fffdf2',.7);check.colorNode=sin(uv().x.mul(20*Math.PI)).mul(sin(uv().y.mul(4*Math.PI))).greaterThan(0).select(vec3(.85),vec3(.024));const start=this.add(this.world,new THREE.PlaneGeometry(15,1.15),check,[track.road[0],.024,2]);start.rotation.x=-Math.PI/2;start.rotation.z=Math.PI/2;start.castShadow=false;
 const tireG=this.own(new THREE.CylinderGeometry(.65,.70,.86,20)),tireM=this.material('#171c20',.93);const tires=new THREE.InstancedMesh(tireG,tireM,track.obstacles.length/4),o=new THREE.Object3D();for(let i=0;i<tires.count;i++){o.position.set(track.obstacles[i*4],.43,track.obstacles[i*4+2]);o.updateMatrix();tires.setMatrixAt(i,o.matrix);}tires.castShadow=true;tires.receiveShadow=true;this.world.add(tires);
 let seed=7419;const rand=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;};
 const rocks=new THREE.InstancedMesh(this.own(new THREE.IcosahedronGeometry(1,2)),this.material('#85867e',.94),200);for(let i=0;i<rocks.count;i++){const t=rand()*Math.PI*2,p=trackPoint(t),b=trackPoint(t+.001),l=Math.hypot(b.x-p.x,b.z-p.z),side=rand()>.5?1:-1,d=18+rand()*110;o.position.set(p.x+(b.z-p.z)/l*d*side,.2,p.z-(b.x-p.x)/l*d*side);const r=.5+rand()*2.9;o.scale.set(r,r*(.55+rand()),r*(.7+rand()));o.rotation.set(rand(),rand()*6,rand());o.updateMatrix();rocks.setMatrixAt(i,o.matrix);}rocks.castShadow=true;rocks.receiveShadow=true;this.world.add(rocks);o.scale.set(1,1,1);o.rotation.set(0,0,0);
 const leavesM=this.material('#263e2a',.88),barkM=this.material('#3c3428',.95),trunks=new THREE.InstancedMesh(this.own(new THREE.CylinderGeometry(.20,.32,4,8)),barkM,180),crowns=new THREE.InstancedMesh(this.own(new THREE.IcosahedronGeometry(1,2)),leavesM,540);
 for(let i=0;i<180;i++){const t=rand()*Math.PI*2,p=trackPoint(t),next=trackPoint(t+.01),l=Math.hypot(next.x-p.x,next.z-p.z),side=i%3===0?1:-1,dist=18+rand()*95,x=p.x+(next.z-p.z)/l*dist*side,z=p.z-(next.x-p.x)/l*dist*side,scale=.7+rand()*1.2;o.position.set(x,2*scale,z);o.scale.set(scale,scale,scale);o.rotation.set(0,rand()*6,0);o.updateMatrix();trunks.setMatrixAt(i,o.matrix);for(let j=0;j<3;j++){o.position.set(x+(rand()-.5)*2,3.4*scale+j*.7,z+(rand()-.5)*2);o.scale.set(scale*(1.6+rand()*.6),scale*1.5,scale*1.8);o.updateMatrix();crowns.setMatrixAt(i*3+j,o.matrix);}}
 trunks.castShadow=true;crowns.castShadow=true;crowns.receiveShadow=true;this.world.add(trunks,crowns);
 const mountMat=this.material('#66747c',1);for(let i=0;i<24;i++){const a=i/24*Math.PI*2,r=1100+rand()*300,h=100+rand()*220;const m=this.add(this.world,new THREE.ConeGeometry(170+rand()*150,h,9,6),mountMat,[Math.cos(a)*r,h*.44-20,Math.sin(a)*r]);m.rotation.y=rand()*6;m.castShadow=false;}
 // Outdoor architecture is deliberately lightweight; the car owns the detail budget.
 const concrete=this.material('#666b6c',.83),metal=this.material('#3c4146',.42,.45);for(let j=0;j<4;j++){this.add(this.world,new THREE.BoxGeometry(18,5,12),concrete,[268,2.5,-38+j*18]);this.add(this.world,new THREE.BoxGeometry(.18,3.4,10),metal,[258.89,1.7,-38+j*18]);this.add(this.world,new THREE.BoxGeometry(21,.2,14),this.material('#a3a7a6',.4,.4),[267,5.08,-38+j*18]);}
 const ocean=this.material('#3a7682',.22,.25);ocean.normalNode=vec3(sin(positionWorld.x.mul(.015).add(this.time)).mul(.025),float(1),cos(positionWorld.z.mul(.019).add(this.time.mul(.6))).mul(.025));const sea=this.add(this.world,new THREE.PlaneGeometry(1800,3000),ocean,[1390,-.13,0]);sea.rotation.x=-Math.PI/2;sea.castShadow=false;
 }
 makeEffects(){const sim=this.sim,p=sim.smoke.node.element(instanceIndex),m=this.own(new THREE.SpriteNodeMaterial({transparent:true,depthWrite:false,opacity:.15,color:'#bfc2c3'}));m.positionNode=p.xyz;m.scaleNode=float(1).sub(p.w).mul(.70).add(.18);m.opacityNode=float(1).sub(smoothstep(.08,.5,uv().sub(.5).length())).mul(p.w).mul(.16);this.smoke=new THREE.Sprite(m);this.smoke.count=sim.smokeCount;this.smoke.frustumCulled=false;this.world.add(this.smoke);
 const ix=instanceIndex.mul(2),a=sim.marks.node.element(ix),b=sim.marks.node.element(ix.add(1)),x=positionLocal.x.mul(b.y),z=positionLocal.y.mul(b.z),sm=this.own(new THREE.MeshBasicNodeMaterial({color:'#101113',transparent:true,depthWrite:false,side:THREE.DoubleSide}));sm.positionNode=vec3(a.x.add(cos(b.x).mul(x)).add(sin(b.x).mul(z)),a.y,a.z.sub(sin(b.x).mul(x)).add(cos(b.x).mul(z)));sm.opacityNode=a.w.mul(clamp(float(1).sub(this.time.sub(b.w).div(80)),0,1));const skids=new THREE.InstancedMesh(this.own(new THREE.PlaneGeometry(1,1)),sm,sim.markCount);skids.frustumCulled=false;this.world.add(skids);}
 setMode(mode){this.mode=mode;const studio=mode==='garage';this.studio.visible=studio;this.world.visible=!studio;this.scene.environment=this.car.quality==='light'?null:(studio?this.env.studio:this.env[this.lightMode]);this.scene.environmentIntensity=studio?.8:1;this.car.envNode.value=studio?this.env.studio:this.env[this.lightMode];this.scene.background=studio?new THREE.Color('#3a4148'):this.env[this.lightMode];this.scene.backgroundBlurriness=0;this.scene.environmentIntensity=studio?1.05:1.1;this.scene.fog=null;this.applyLighting();}
 setLighting(name){if(!['day','golden','night'].includes(name))return;this.lightMode=name;if(this.mode!=='garage')this.setMode(this.mode);}
 applyLighting(){const studio=this.mode==='garage',night=!studio&&this.lightMode==='night',gold=!studio&&this.lightMode==='golden';this.sun.color.set(studio?'#fff0db':gold?'#ffd8a3':'#edf3ff');this.sun.intensity=night?.10:gold?2.4:1.8;this.ambient.intensity=night?.06:studio?.45:.48;this.car.sunStrength.value=this.sun.intensity;this.car.sunColor.value.copy(this.sun.color);this.car.lamps.value=1;}
 update(state,dt){this.time.value=state[15];this.car.brake.value=Math.max(state[22],state[23]);this.wet.value=this.sim.parameters.wetness;const x=state[0],z=state[2];this.sun.position.set(x-12,18,z+9);this.sun.target.position.set(x,0,z);const yaw=state[3],s=Math.sin(yaw),c=Math.cos(yaw),night=this.mode!=='garage'&&this.lightMode==='night';this.headlights.forEach((l,i)=>{const wx=i===0?-.68:.68;l.intensity=night?65:0;l.visible=night&&i===0;l.position.set(x+c*wx+s*2,.62,z-s*wx+c*2);l.target.position.set(x+c*wx+s*35,.1,z-s*wx+c*35);});}
 dispose(){for(const r of this.resources)r.dispose();for(const t of Object.values(this.env))t.dispose();this.scene.clear();}
}
